### PR TITLE
fix: do not build docs for external projects

### PR DESCRIPTION
**Pull request by FrogTheFrog**
## Description
Do not build docs for external projects. Sunshine and libdd are fighting over target names otherwise.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Review by ReenigneArcher — COMMENTED** [review]
Could you make this change to https://github.com/LizardByte/tray as well?

Otherwise, I need to wait to merge this until I can get to that.

**Comment by ReenigneArcher** [comment]
This might be a hint as to the issues with coverage in the this repo. 
image

**Comment by FrogTheFrog** [comment]
> This might be a hint to the issues with coverage in the this repo. image

On MacOS it simply failed to upload...

**Comment by ReenigneArcher** [comment]
That was Linux: 
image

**Pull request merged**
